#!/usr/bin/env bash
# Install and configure the local WordPress, then write the credentials the publisher needs.
#
# Safe to run repeatedly: every step checks before it acts, so re-running after a container
# restart repairs the site rather than duplicating anything.
#
#   docker compose up -d && ./bootstrap.sh
#
# To start over from nothing:  docker compose down -v

set -euo pipefail

cd "$(dirname "$0")"

# Must agree with the port docker-compose.yml publishes, because WordPress stores this URL
# in the database and serves redirects from it.
WP_PORT="${WP_PORT:-8080}"
SITE_URL="http://localhost:${WP_PORT}"
ADMIN_USER="admin"
# Localhost only, never reachable from outside this machine, and the volume is disposable.
# A generated secret here would only be a secret from the person who needs to log in.
ADMIN_PASSWORD="admin"
EDITOR_USER="editor"
EDITOR_PASSWORD="editor"
APP_PASSWORD_NAME="publisher"
ENV_FILE=".env"

wp() {
  docker compose run --rm -T cli wp "$@"
}

echo "==> Waiting for WordPress files and database"
for _ in $(seq 1 30); do
  if wp core version >/dev/null 2>&1; then
    break
  fi
  sleep 2
done

if wp core is-installed >/dev/null 2>&1; then
  echo "==> WordPress is already installed"
else
  echo "==> Installing WordPress"
  wp core install \
    --url="$SITE_URL" \
    --title="StudCraft (local)" \
    --admin_user="$ADMIN_USER" \
    --admin_password="$ADMIN_PASSWORD" \
    --admin_email="admin@studcraft.test" \
    --skip-email
fi

# Pretty permalinks are not a preference here: the whole publication design is a slug
# hierarchy, and the default ?p=123 permalink cannot express one.
echo "==> Setting permalinks to /%postname%/"
wp rewrite structure '/%postname%/' --hard
wp rewrite flush --hard

# The container defines WP_HOME and WP_SITEURL from its environment on every request, so the
# served site already follows WP_PORT. These two options are the copy in the database, which
# nothing overrides for WP-CLI — left alone they keep reporting the port the site was first
# installed on, and every `wp` command then disagrees with the site about where it lives.
echo "==> Pointing the stored site URL at $SITE_URL"
wp option update home "$SITE_URL" >/dev/null
wp option update siteurl "$SITE_URL" >/dev/null

if wp user get "$EDITOR_USER" >/dev/null 2>&1; then
  echo "==> Editor user already exists"
else
  echo "==> Creating the editor user, to review what is staged before it goes public"
  wp user create "$EDITOR_USER" "editor@studcraft.test" \
    --role=editor --user_pass="$EDITOR_PASSWORD"
fi

# Application Passwords are core since WordPress 5.6. They are what lets the publisher
# authenticate over the REST API without holding the account's real password.
echo "==> Issuing an application password for the publisher"
wp user application-password delete "$ADMIN_USER" --all >/dev/null 2>&1 || true
APP_PASSWORD="$(wp user application-password create "$ADMIN_USER" "$APP_PASSWORD_NAME" --porcelain | tr -d '\r')"

cat > "$ENV_FILE" <<ENV
# Generated by bootstrap.sh. Git-ignored. Local throwaway credentials only.
WP_BASE_URL=$SITE_URL
WP_USER=$ADMIN_USER
WP_APP_PASSWORD="$APP_PASSWORD"
ENV

echo
echo "WordPress is ready."
echo "  Site        $SITE_URL"
echo "  Admin       $SITE_URL/wp-admin  ($ADMIN_USER / $ADMIN_PASSWORD)"
echo "  Editor      $EDITOR_USER / $EDITOR_PASSWORD"
echo "  Credentials $(pwd)/$ENV_FILE"
